# Generated by Django 4.2.3 on 2025-08-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIServer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergenComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_id', models.CharField(max_length=20)),
                ('component', models.CharField(max_length=100)),
                ('food_class', models.CharField(max_length=50)),
                ('species_key', models.CharField(max_length=100)),
                ('species_name', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'allergen_components',
            },
        ),
    ]
